" Generated by vim-plug
" Tue 21 Jun 2022 06:24:13 PM UTC
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['a.vim'].commit = '2cbe946206ec622d9d8cf2c99317f204c4d41885'
silent! let g:plugs['ale'].commit = '91e8422d6d67f1b1139b57b8707945ea2531443e'
silent! let g:plugs['deoplete.nvim'].commit = '33ed4fa0cd704999f9f74b37640bf6d7334bac37'
silent! let g:plugs['fzf'].commit = 'bad724d5f8c45ccdca405d9e394afc2174cd22ce'
silent! let g:plugs['fzf.vim'].commit = 'f86ef1bce602713fe0b5b68f4bdca8c6943ecb59'
silent! let g:plugs['indentLine'].commit = '7753505f3c500ec88d11e9373d05250f49c1d900'
silent! let g:plugs['my-colors-light'].commit = 'ab344696c4cd33253f8d80cc5b28aa0b57cd4c55'
silent! let g:plugs['neoview'].commit = '2cfa3737cedc3cd27c64fa78a835323446e56dda'
silent! let g:plugs['nvim-yarp'].commit = 'bb5f5e038bfe119d3b777845a76b0b919b35ebc8'
silent! let g:plugs['python-syntax'].commit = '2cc00ba72929ea5f9456a26782db57fb4cc56a65'
silent! let g:plugs['unite.vim'].commit = 'b08814362624ded3b462addba4711647879ca308'
silent! let g:plugs['vim-bbye'].commit = '25ef93ac5a87526111f43e5110675032dbcacf56'
silent! let g:plugs['vim-cpp-enhanced-highlight'].commit = '6e421c75fb5fa9fe68d3d4913bdd7ae6f44be364'
silent! let g:plugs['vim-flatbuffers'].commit = '95c828bcc7dd83627f732bbb1d78888a3a870d6e'
silent! let g:plugs['vim-go'].commit = 'b7506c6da8ea3a88e268a91aa6630be3e26a20a9'
silent! let g:plugs['vim-hug-neovim-rpc'].commit = '93ae38792bc197c3bdffa2716ae493c67a5e7957'
silent! let g:plugs['vim-oscyank'].commit = 'adedd98f125d7507a1306cbbc8ec658aa29396db'

PlugUpdate!

